name: CI

on:
  push:

jobs:
  linux-ci:
    name: Linux CI
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    steps:
      - name: Download repository
        if: ${{ env.should_run == 1 }}
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive

      - name: Build Release
        if: github.ref_type == 'tag'
        run: |
          touch release-artifact.txt

      - name: Upload release
        if: github.ref_type == 'tag'
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: release-artifact.txt